# Generated by Django 2.0.7 on 2018-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180709_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='letter_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
