# Generated by Django 2.0.7 on 2018-07-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180709_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
