# Generated by Django 2.0.7 on 2018-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='letter_end',
            field=models.TextField(blank=True, null=True),
        ),
    ]
