# Generated by Django 2.0.7 on 2018-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_event_letter_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizers'),
        ),
    ]
